apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-processor
  template:
    metadata:
      labels:
        app: image-processor
    spec:
      containers:
        - image: meshetr/image-processor:v1.0
          name: image-processor
          ports:
            - containerPort: 50051
              name: server
              protocol: TCP
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: database
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: database
                  key: password
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: database
                  key: port
            - name: DB_SSL
              valueFrom:
                secretKeyRef:
                  name: database
                  key: ssl
            - name: DB_TIMEZONE
              valueFrom:
                secretKeyRef:
                  name: database
                  key: timezone
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database
                  key: name
            - name: GCP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-storage-client
                  key: credentials-json
            - name: KRAKEN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: kraken
                  key: key
            - name: KRAKEN_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: kraken
                  key: secret
            - name: IMAGERESIZER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: imageresizer
                  key: key
---

apiVersion: v1
kind: Service
metadata:
  name: image-processor-service
spec:
  ports:
    - port: 50051
      protocol: TCP
      targetPort: server
  selector:
    app: image-processor
