apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-processor
  template:
    metadata:
      labels:
        app: image-processor
    spec:
      containers:
        - image: meshetr/image-processor:v0.1
          name: image-processor
          ports:
            - containerPort: 50051
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: image-processor-service
spec:
  ports:
    - port: 50051
      protocol: TCP
      targetPort: server
  selector:
    app: image-processor
